name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Install project dependencies
      - name: Install dependencies
        run: npm ci --force

      # Install Chromium browser only (with dependencies)
      - name: Install Chromium Browser only
        run: npx playwright install chromium --with-deps --force

      # Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test --project=chromium --max-failures=1

      # Upload Playwright test report as artifact (for download and review)
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1

      # Deploy Playwright test report to GitHub Pages for visual access
      - name: Deploy Playwright report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report 
          destination_dir: /  
