name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Install project dependencies
      - name: Install dependencies
        run: npm ci --force

      # Install Chromium browser only (with dependencies)
      - name: Install Chromium Browser only
        run: npx playwright install chromium --with-deps --force

      # Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test --project=chromium --reporter=html --max-failures=1

      # Generate Allure report
      - name: Generate Allure Report
        run: npx allure generate allure-results --clean -o allure-report

      # Prepare public folder for deployment
      - name: Prepare public folder
        run: |
          mkdir public
          mv playwright-report public/playwright-report
          mv allure-report public/allure-report

      # Deploy both Playwright and Allure reports to GitHub Pages
      - name: Deploy Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_1 }}
          publish_dir: ./public
          publish_branch: gh-pages
          clean: true
